language: java
sudo: false
before_script:
- cd demo
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sauce_connect: true
env:
  global:
  - secure: wZgv0jjNAjOdypLmXrcTVCGiATwVwfjkmzGdjTrKp0V9hgWqJIBTUopkcymN8SV7PqRHfEP+NhX8Zb50+oRRTWKTGvwly0LTXvt7rSKzC9mCTd535ITAEgKD1dQzDod/14n5kuiuUB3wijuhTBpI1VC5/5JJnSPNZU2omqXL4Zgfl30+SH1DD010X1RoW1MI90nLOULH/1h77+erSTBzi6IakIRqAa3Y90D/y09nKFjpbCo0U6IADAG+j9PS1KfvzIECS0RssSPR8Bn8g/fMVAr41MwsxJWGdt4TrKygRAo1aOPYq1vCb2ank9SJvQhznio6t/BJa51kICNZH8NVFYO1jmuh6O1YPsz7VAZsDQuigWWSD98nrV94JErc3DQAOwhSivn+ZJc6c/wv3X1ozjUxmRgP3wFSZdzM7gslSqnXbv09p8Ln0kMso9C5IQPCkwLorI/qz+AffRb73HEYwftQaYqjMJTA7GkCiNRz2/m+/qFQDaOe2irogTVoJmc34W1zHOBBPIjE5qfwnv9k8QCj/qyo3BO4YA6LBHmtTSNaabPjIzRjrkuznz5PnpnvKEiuB+sF2eG5nUmf2rl1gwG4idnVGJdxliQnIFUhDvzOK1xR1aely7+lv/TxV9PjpJ3w3kr1bWQoygLAk/z5eY8W5WfA2JJXMXv36bvWW4Y=
  - secure: xpO0WAIq/gwTU9ojClJfvJZjqQOKdURVDt2NAMGM/UNH3CD6oMpl83jqBl29ABgOodyNyb4iM1skNN9yxPvoMwPilaEnEKD8ij9BLGDyxL7ikdDoKuMu966KiSLSvMNPXJDkTeLKE7XHsVYp4EV+rcQDcsix8odLekif/+n1VpO4qY8vyHan5C/rJ9VCa4ohyK6/GBMfTcuNQmTtU1tOHNeCjUgswDnm9QWu8B5AavSbid1jZ7Dip4enjvUaBg9ItCjf8kmXkPlu7rtQh7zdSRcjwzdgptqw+ZDWkFO6Pljrinh4kOsyCB36gdN0jH6X8prXvjQtiDKualO4g7EYiwlStk4dKsfZj51qa1oKcEGSmuihU1FLmRFclFwz/CkWQsXzGV0ooHZsYarpV+G20o5PrmBlYp3bqFdMYMHnJ+CzvBdLj+CDa9VtaV2XV/8b00B1hnrYxHtbaVnL2LWxEhlUX1uQFHE3QG1LmIBpNX8oRhPjT2xZXmtn5tNCeb0Bln/tdZZoh9w2SKg5YYXmlDM7bfIMU5SHnqFfEDniQxG7URRfjf1HWvyF2gt3dg4L1rCCq8btuKDjplfY7o4VhHHxmCDT3vMrHbnvTYkvLyJ7XP/qbhriAAosMXkOvw4b65MRhai0I/QVKgPbpJSW6n9TUIUXIrYwPL9GwF1c5CE=
